all: serv checkopts checkifs ping4 ping6

serv: serv.c
	gcc serv.c -O2 -o serv

checkopts: checkopts.c
	gcc checkopts.c -O2 -o checkopts

checkifs: checkifs.c
	gcc checkifs.c -O2 -o checkifs

ping4: ping4.c
	gcc ping4.c -O2 -o ping4

ping6: ping6.c
	gcc ping6.c -O2 -o ping6
