all: serv checkopts checkifs ping6

serv: serv.c
	gcc serv.c -O2 -o serv

checkopts: checkopts.c
	gcc checkopts.c -O2 -o checkopts

checkifs: checkifs.c
	gcc checkifs.c -O2 -o checkifs

ping6: ping6.c
	gcc ping6.c -O2 -o ping6
