all: serv mreq checkopts checkifs

serv: serv.c
	gcc serv.c -O2 -o serv

mreq: mreq.c
	gcc mreq.c -O2 -o mreq

checkopts: checkopts.c
	gcc checkopts.c -O2 -o checkopts

checkifs: checkifs.c
	gcc checkifs.c -O2 -o checkifs
